"""Setting default role for users as 'user'

Revision ID: 1a4d63d2d9db
Revises: 3c24d699c16c
Create Date: 2026-04-08 22:16:09.126567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1a4d63d2d9db"
down_revision: Union[str, Sequence[str], None] = "3c24d699c16c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.INTEGER(),
        server_default="1",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
