"""add email column to users

Revision ID: 2d3648de6b45
Revises: 50a68269af26
Create Date: 2026-09-19 20:41:33.080479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = "2d3648de6b45"
down_revision: Union[str, Sequence[str], None] = "50a68269af26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add email column as nullable first
    op.add_column(
        'users',
        sa.Column('email', sa.String(255), nullable=True)
    )

    # Populate existing rows with unique placeholder emails based on user ID
    users_table = table('users',
        column('id', sa.Integer),
        column('email', sa.String(255))
    )

    op.execute(
        sa.text("UPDATE users SET email = id || '_placeholder@example.com'")
    )

    # Now make the column not nullable and unique
    op.alter_column(
        'users',
        'email',
        nullable=False
    )

    op.create_unique_constraint(
        'uq_users_email',
        'users',
        ['email']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
