"""replace category table with status column

Revision ID: 5037b334f909
Revises: 38569b944b97
Create Date: 2026-04-17 11:29:47.801503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "5037b334f909"
down_revision: Union[str, Sequence[str], None] = "38569b944b97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("tasks_category_id_fkey"), "tasks", type_="foreignkey"
    )
    op.drop_table("categories")
    task_status_enum = postgresql.ENUM(
        "todo", "in_progress", "done",
        name="task_status"
    )
    task_status_enum.create(op.get_bind())
    op.add_column(
        "tasks",
        sa.Column(
            "status",
            task_status_enum,
            server_default="todo",
            nullable=False,
        ),
    )
    op.drop_column("tasks", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("category_id", sa.Integer(), nullable=True)
    )

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
    )

    op.create_foreign_key(
        op.f("tasks_category_id_fkey"),
        "tasks",
        "categories",
        ["category_id"],
        ["id"],
    )

    op.drop_column("tasks", "status")

    task_status_enum = postgresql.ENUM(
        "todo", "in_progress", "done",
        name="task_status"
    )
    task_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
