"""add family_created_at column to refresh tokens table

Revision ID: 50a68269af26
Revises: cb7197378bc8
Create Date: 2026-08-19 21:09:19.015262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "50a68269af26"
down_revision: Union[str, Sequence[str], None] = "cb7197378bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "family_created_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE refresh_tokens
        SET family_created_at = NOW()
        WHERE family_created_at IS NULL
        """
    )

    op.alter_column(
        "refresh_tokens",
        "family_created_at",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "family_created_at")
    # ### end Alembic commands ###
